# Generated by Django 4.1.1 on 2022-09-12 05:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_empleado_avatar_empleado_habilidades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['last_name'], 'verbose_name': 'Mis Empleados', 'verbose_name_plural': 'Empleados de la empresa'},
        ),
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidades', 'verbose_name_plural': 'Habilidades de los empleados'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='CV'),
            preserve_default=False,
        ),
    ]
