# Generated by Django 4.1.1 on 2022-09-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_alter_empleado_options_alter_habilidades_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Full Name'),
        ),
    ]
